#!/usr/bin/bash

# convert video to webm format using ffmpeg

if [ $# -ne 2 ]
then
	echo "Usage: convert-webm <input-file> <output-file>"
else
	ffmpeg  -i $1 -b:v 0  -crf 30  -pass 1  -an -f webm /dev/null && ffmpeg  -i $1 -b:v 0  -crf 30  -pass 2 $2
fi
